### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ae-bii** [ae-bii/neural-geometry#5]
This is Neural Geometry's official roadmap and progress tracker.

### Contributor Guide

There's lots to be done to make this an awesome library. Feel free to tackle any of these items listed here!

# TODO

- [x] Get version 0.1.0 ready for use.
- [x] Add GPU support.
- [x] Add basic tests with GitHub action.
- [x] Rebrand to general Neural Geometry library.
- [x] Add GitHub action for automatic publishing to PyPI.
- [ ] Add Bayesian optimizer.
- [ ] Explore variations of random walks with simulated annealing.
- [ ] Rewrite in C/C++  with Python bindings.

**Comment by kzqiu** [comment]
Completed fixing GPU support on 2024-07-08.
